# Site settings
title: Srihari Sankar Sahu
email: sriharisahu@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  This website is just a rendition for a online resume updated on a monthly basis
  for the Full Stack Web Developer named Srihari Sankar Sahu.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sriharisahu.github.io" # the base hostname & protocol for your site
twitter_username: srihari_sahu
github_username:  sriharisahu

# Build settings
markdown: kramdown
